name: 'customer_analytics'
version: '1.0.0'
profile: 'customer_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  customer_analytics:
    staging:
      +materialized: table
      +schema: staging       # staging tables go to Snowflake schema 'staging'
    analytics:
      +materialized: table
      +schema: analytics     # analytics tables go to Snowflake schema 'analytics'
